
const fighters = [
    "mario",
    "donkey_kong",
    "link",
    "samus",
    "dark_samus",
    "yoshi",
    "kirby",
    "fox",
    "pikachu",
    "luigi",
    "ness",
    "captain_falcon",
    "jigglypuff",
    "peach",
    "daisy",
    "bowser",
    "ice_climbers",
    "sheik",
    "zelda",
    "dr_mario",
    "pichu",
    "falco",
    "marth",
    "lucina",
    "young_link",
    "ganondorf",
    "mewtwo",
    "roy",
    "chrom",
    "mr_game_and_watch",
    "meta_knight",
    "pit",
    "dark_pit",
    "zero_suit_samus",
    "wario",
    "snake",
    "ike",
    "pokemon_trainer",
    "diddy_kong",
    "lucas",
    "sonic",
    "king_dedede",
    "olimar",
    "lucario",
    "rob",
    "toon_link",
    "wolf",
    "villager",
    "mega_man",
    "wii_fit_trainer",
    "rosalina_and_luma",
    "little_mac",
    "greninja",
    "mii_brawler",
    "mii_swordfighter",
    "mii_gunner",
    "palutena",
    "pac_man",
    "robin",
    "shulk",
    "bowser_jr",
    "duck_hunt",
    "ryu",
    "ken",
    "cloud",
    "corrin",
    "bayonetta",
    "inkling",
    "ridley",
    "simon",
    "richter",
    "king_k_rool",
    "isabelle",
    "incineroar",
    "piranha_plant",
    "joker",
    "hero",
    "banjo_and_kazooie",
    "terry",
    "byleth"
]

const displayNameEn = [
    "mario",
    "donkey kong",
    "link",
    "samus",
    "dark samus",
    "yoshi",
    "kirby",
    "fox",
    "pikachu",
    "luigi",
    "ness",
    "captain falcon",
    "jigglypuff",
    "peach",
    "daisy",
    "bowser",
    "ice climbers",
    "sheik",
    "zelda",
    "dr. mario",
    "pichu",
    "falco",
    "marth",
    "lucina",
    "young link",
    "ganondorf",
    "mewtwo",
    "roy",
    "chrom",
    "mr. game & watch",
    "meta knight",
    "pit",
    "dark pit",
    "zero suit samus",
    "wario",
    "snake",
    "ike",
    "pokemon trainer",
    "diddy kong",
    "lucas",
    "sonic",
    "king dedede",
    "olimar",
    "lucario",
    "rob",
    "toon link",
    "wolf",
    "villager",
    "mega man",
    "wii fit trainer",
    "rosalina & luma",
    "little mac",
    "greninja",
    "mii brawler",
    "mii swordfighter",
    "mii gunner",
    "palutena",
    "pac man",
    "robin",
    "shulk",
    "bowser jr.",
    "duck hunt",
    "ryu",
    "ken",
    "cloud",
    "corrin",
    "bayonetta",
    "inkling",
    "ridley",
    "simon",
    "richter",
    "king k. rool",
    "isabelle",
    "incineroar",
    "piranha plant",
    "joker",
    "hero",
    "banjo & kazooie",
    "terry",
    "byleth"
]


const displayNameJp = [
    "マリオ",
    "ドンキーコング",
    "リンク",
    "サムス",
    "ダークサムス",
    "ヨッシー",
    "カービィ",
    "フォックス",
    "ピカチュウ",
    "ルイージ",
    "ネス",
    "キャプテン・ファルコン",
    "プリン",
    "ピーチ",
    "デイジー",
    "クッパ",
    "アイスクライマー",
    "シーク",
    "ゼルダ",
    "ドクターマリオ",
    "ピチュー",
    "ファルコ",
    "マルス",
    "ルキナ",
    "こどもリンク",
    "ガノンドロフ",
    "ミュウツー",
    "ロイ",
    "クロム",
    "Mr.ゲーム&ウォッチ",
    "メタナイト",
    "ピット",
    "ブラックピット",
    "ゼロスーツサムス",
    "ワリオ",
    "スネーク",
    "アイク",
    "ポケモントレーナー",
    "ディディーコング",
    "リュカ",
    "ソニック",
    "デデデ",
    "ピクミン&オリマー",
    "ルカリオ",
    "ロボット",
    "トゥーンリンク",
    "ウルフ",
    "むらびと",
    "ロックマン",
    "Wii Fit トレーナー",
    "ロゼッタ&チコ",
    "リトル・マック",
    "ゲッコウガ",
    "Miiファイター 格闘",
    "Miiファイター 剣術",
    "Miiファイター 射撃",
    "パルテナ",
    "パックマン",
    "ルフレ",
    "シュルク",
    "クッパJr.",
    "ダックハント",
    "リュウ",
    "ケン",
    "クラウド",
    "カムイ",
    "ベヨネッタ",
    "インクリング",
    "リドリー",
    "シモン",
    "リヒター",
    "キングクルール",
    "しずえ",
    "ガオガエン",
    "パックンフラワー",
    "ジョーカー",
    "勇者",
    "バンジョー&カズーイ",
    "テリー",
    "ベレト/べレス"
]


export { fighters, displayNameEn, displayNameJp };